// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ho3vJ3u6wmwQgFRnADB8djEjRenhqjI',
    appId: '1:800002913299:web:79abbf76f708afa773bbe6',
    messagingSenderId: '800002913299',
    projectId: 'kinconnectt',
    authDomain: 'kinconnectt.firebaseapp.com',
    storageBucket: 'kinconnectt.firebasestorage.app',
    measurementId: 'G-FNL1VB48HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUMOLxUYjTjqzt_u69I7G_PSaB8vB5T5w',
    appId: '1:800002913299:android:f4f6791d21f695f373bbe6',
    messagingSenderId: '800002913299',
    projectId: 'kinconnectt',
    storageBucket: 'kinconnectt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnzIUjjCYzeNXyR34FPcTpyvNQTqBLsc',
    appId: '1:800002913299:ios:dae7b42b038f190a73bbe6',
    messagingSenderId: '800002913299',
    projectId: 'kinconnectt',
    storageBucket: 'kinconnectt.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnzIUjjCYzeNXyR34FPcTpyvNQTqBLsc',
    appId: '1:800002913299:ios:dae7b42b038f190a73bbe6',
    messagingSenderId: '800002913299',
    projectId: 'kinconnectt',
    storageBucket: 'kinconnectt.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ho3vJ3u6wmwQgFRnADB8djEjRenhqjI',
    appId: '1:800002913299:web:389375c08c136aa973bbe6',
    messagingSenderId: '800002913299',
    projectId: 'kinconnectt',
    authDomain: 'kinconnectt.firebaseapp.com',
    storageBucket: 'kinconnectt.firebasestorage.app',
    measurementId: 'G-CVCWGQV852',
  );
}
